# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :firebase_stg do
      sh "cd .. && npm run build:android:stg"
      firebase_app_distribution(
        android_artifact_type: "APK",
        android_artifact_path: "app/build/outputs/apk/staging/release/app-staging-release.apk",
        service_credentials_file: "../firebase_credentials.json",
        app: "1:525722211968:android:b8ca8704fdc88c4a2df865",
        groups: "testers",
        release_notes: "Fine Me Android stg",
    )

  end

  lane :firebase_prd do
      sh "cd .. && npm run build:android:prd"
      firebase_app_distribution(
        android_artifact_type: "APK",
        android_artifact_path: "app/build/outputs/apk/production/release/app-production-release.apk",
        service_credentials_file: "../firebase_credentials.json",
        app: "1:525722211968:android:bb1fc1a3778924552df865",
        groups: "testers",
        release_notes: "Fine Me Android prd",
    )
  end
end
